### ISSUE TITLE
DayChildVC data sync 

### ISSUE THREAD

**Issue by hyex** [ProjectInTheClass/PinkyPromise#32]
업데이트가 느림
cell 파일에서 DispatchQueue.main.async 사용함

**Comment by hyex** [comment]
파이어베이스에서 데이터를 가져올 때, 디바이스에 저장되는 캐시? 같은 게 있음
뷰를 보여줄 때 캐시를 먼저 띄우고 서버에서 가져온 데이터로 업데이트 해주면 된다

**Comment by odyflame** [comment]
로컬캐시를 설정은 했지만 제대로 되는지 확인못함 사진은 어떻게 하는지 잘모르겠음 나중에 수정예정
